version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
    target-branch: dev
    groups:
      npm-deps:
        update-types: [minor, patch]
    ignore:
      # We will be updating major versions manually
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
    target-branch: dev
