import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { env as serverEnv } from '@/env/server';
import AuthenticatorWrapper from './authenticator-wrapper';
import ConfigureAmplifyClient from './configure-amplify-client';
import './globals.css';
import '@aws-amplify/ui-react/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen grid justify-center items-center">
          <p>
            Server variable:
            {serverEnv.VARIABLE}
          </p>
          <ConfigureAmplifyClient />
          <AuthenticatorWrapper>
            {children}
          </AuthenticatorWrapper>
        </main>
      </body>
    </html>
  );
}
